# Generated by Django 3.2.3 on 2021-05-27 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0002_auto_20210527_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('released', models.DateField()),
                ('year', models.IntegerField()),
                ('sentiment', models.IntegerField(null=True)),
                ('poster', models.ImageField(blank=True, upload_to='movies/')),
                ('total_reviews', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'movies_list',
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('sentiment', models.IntegerField(null=True)),
                ('posted', models.DateTimeField(auto_now=True)),
                ('critic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.profile')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
    ]
